version: "3.9"

services:
  bot:
    build: .
    command: node dist/main.bot.js
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  api:
    build: .
    command: node dist/main.api.js
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GEMINI_API_KEY=${GEMINI_API_KEY}